---
# To use the when: syntax in a playbook use the command (ansible all -m gather_facts --limit [IP] | grep ansible_distribution to get some info regarding the OS.
- hosts: all
  become: true
  tasks:

  - name: update repo index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"   

  - name: install neofetch package
    dnf:
      name: neofetch
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: add gedit package
    dnf:
      name: gedit
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

# Next line IP dont exist | let's assume the IP belongs to a ubuntu machine

#- name: install apache2 and php for Ubuntu
#   apt:
#     name: 
#      - apache2
#      - libapache2-mod-php      
#     state: latest
#   when: ansible_distribution == "Ubuntu"
