---
# To use the when: syntax in a playbook use the command (ansible all -m gather_facts --limit [IP] | grep ansible_distribution to get some info regarding the OS.
- hosts: all
  become: true
  tasks:

  - name: update repo index
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"   

  - name: install neofetch package
    tags: neofetch,Fedora
    dnf:
      name: neofetch
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: add gedit package
    tags: gedit,Fedora
    dnf:
      name: gedit
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: installing apache2 Fedora
    tags: httpd,Fedora
    dnf: 
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

# Next line IP dont exist | let's assume the IP belongs to a ubuntu machine

#- name: install apache2 and php for Ubuntu
#   apt:
#     name: 
#      - apache2
#      - libapache2-mod-php      
#     state: latest
#   when: ansible_distribution == "Ubuntu"
