---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Fedora)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: update repo cache (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create rr user
    tags: always
    user:
      name: rr
      groups: root

  - name: add ssh key for rr
    tags: always
    authorized_key:
      user: rr
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDoFLvvOGXIp8uLGCHVxcO9gy7YvRWzivWsuraAXgmTN Ansible"

  - name: add sudoers file for rr
    tags: always
    copy:
      src: sudoers_rr
      dest: /etc/sudoers.d/rr
      owner: root
      group: root
      mode: 0440


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web-servers
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for fedora servers
    tags: apache,fedora,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: start httpd (Fedora)
    tags: httpd,apache,fedora
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"

  - name: change e-mail address for admin
    tags: apache,fedora,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin riquelmen1990@live.com
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"  
    register: httpd


  - name: restart httpd (Fedora)
    tags: apache,fedora,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
