---

- hosts: all
  become: true
  tasks:

  - name: Install updates in fedora
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "35"   

  - name: install neofetch and gedit packages all boxes
    package:
      name:
       - "{{ neofetch_package }}"
       - "{{ gedit_package }}" 
      state: latest
      update_cache: yes
